config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users
  root 'contacts#index'

  resources :timerecords
  
  get 'timerecords/timeout/:id' => 'timerecords#timeout'

  
  resources :contacts do
  	resources :locations
    resources :people
  end

  resources :locations do
    resources :signs
  end

  resources :signs do
    resources :sign_details
    resources :jobnumbers
    resources :attributes
  	resources :records
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

  self.abstract_class = true
  $contacts = Contact.all
  d=Date.today
  $beginning_of_this_week = d.at_beginning_of_week-1.day
  $end_of_this_week = d.at_beginning_of_week+6.day

end

app/models/contact.rb
class Contact < ApplicationRecord
	has_many :locations
	has_many :people
	has_many :signs
	has_many :jobnumbers
	has_many :timerecords, through: :jobnumbers
		
  default_scope {order('CompanyName ASC')}
  
		

end

app/models/jobnumber.rb
class Jobnumber < ApplicationRecord
	belongs_to :contact
	belongs_to :sign
	has_many :timerecords
end

app/models/jobnumbers.rb
class Jobnumbers < ActiveRecord::Base
	belongs_to :contact
	belongs_to :sign
	has_many :timerecords
	end

app/models/location.rb
class Location < ApplicationRecord
	belongs_to :contact
	has_many :signs

	scope :matchesContact, ->(id){ where(contact_id: id)}
	

end

app/models/person.rb
class Person < ApplicationRecord
	belongs_to :contact
	
	scope :matchesContact, ->(id){ where(contact_id: id)}
	
end

app/models/record.rb
class Record < ApplicationRecord
	belongs_to :sign
end

app/models/sign.rb
class Sign < ApplicationRecord
	belongs_to :contact
	belongs_to :location, optional: true
	has_many :jobnumbers
	has_many :sign_details
	scope :matchesContactandLocation, ->(id){ where(contact_id: id)}
end

app/models/sign_detail.rb
class SignDetail < ApplicationRecord
	belongs_to :sign
end

app/models/task.rb
class Task < ActiveRecord::Base
	has_many :timerecords
	has_many :users, through: :timerecords
end

app/models/timerecord.rb
class Timerecord < ActiveRecord::Base

	include Filterable

	belongs_to :user
	belongs_to :task

	default_scope {order('timein ASC')}
		
	scope :notimeout, -> {where('timeout IS ?', nil)} 
	scope :timethisweek, -> {where('timein > ?', d).all} 
	scope :weekstart, -> (weekstart){where('timein >= ?', weekstart).all} 
	scope :dateis, -> (date){where('timein = ?', date).all} 
	scope :weekend, -> (weekend){where('timein <= ?', weekend).all} 
	scope :currentuser, ->(user) {where('user_id = ?', user )}
	scope :selecteduser, ->(user) {where('user_id = ?', user )} 
	scope :thisjob, ->(number) {where('jobnumber = ?', number )} 
	scope :tasks_all, ->(taskid){where('task_id = ?', taskid)}
	
	def timeTotal
		if timeout?
			@timeout = timeout
		else
			@timeout = Time.zone.now
		end
		((Time.diff(timein, @timeout, '%m'))[:diff].to_f / 60).round(2)
	end
	
	def day
  		self.timein.strftime('%D')
	end

	d=Time.zone.today
	$timenow = Time.zone.now 
  	$beginning_of_this_week = d.at_beginning_of_week-1.day
  	$end_of_this_week = d.at_beginning_of_week+5.day
  	$beginning_of_last_week = d.at_beginning_of_week-8.day
  	$end_of_last_week = d.at_beginning_of_week-2.day

		
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :timerecords
  has_many :tasks, through: :timerecords

	def fullName
		fullName = "#{firstname} #{lastname}"
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/jobnumbers_helper.rb
module JobnumbersHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/signs_helper.rb
module SignsHelper
end

app/helpers/timerecord_helper.rb
module TimerecordHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SnowContact</title>
    <meta name="viewport" content="initial-scale=1.0001, minimum-scale=1.0001, maximum-scale=1.0001, user-scalable=no"/>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

  <%= render :partial => 'shared/navbar' %>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <div id="wrapper">
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div>
                  <div class="col-sm-1">
                  </div>
                  <div class="col-sm-8">

                     <%= yield %>
                      
                  </div>
                </div>
            </div>
        </div>
  </div>  
  
  </body>
</html>

app/views/layouts/contact.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contact Manager</title>
    <meta name="viewport" content="initial-scale=1.0001, minimum-scale=1.0001, maximum-scale=1.0001, user-scalable=no"/>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application'%>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

  <%= render :partial => 'shared/navbar' %>
  <div id="wrapper">
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div>
                  <div class="col-sm-1">
                  </div>
                  <div class="col-sm-8">

                     <%= yield %>
                      <div id="user_nav">
                      <% if user_signed_in? %>
                      Signed in as <%= current_user.email %>. Not you?
                      <%= link_to "Sign out", destroy_user_session_path %>
                      <% else %>
                      <%= link_to "Sign up", new_user_registration_path %> or
                      <%= link_to "Sign in", new_user_session_path %>
                      <% end %>
                      </div>
                  </div>
                </div>
            </div>
        </div>
    <div id="myContactForm" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>
  </div>  
  
  </body>
</html>

app/views/layouts/loggedin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SnowContact</title>
    <meta name="viewport" content="initial-scale=1.0001, minimum-scale=1.0001, maximum-scale=1.0001, user-scalable=no"/>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <%= render :partial => 'shared/navbar' %>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <div id="wrapper">
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div>
                  <div class="col-sm-1">
                  </div>
                  <div class="col-sm-8">

                     <%= yield %>
                      
                  </div>
                </div>
            </div>
        </div>
  </div>  
  
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PDF</title>
  <%= wicked_pdf_stylesheet_link_tag 'application', media: 'all' %>
</head>
<body>
  <div class='container'>
    <%= yield %>
  </div>

</body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Employee Manager</title>
    <meta name="viewport" content="initial-scale=1.0001, minimum-scale=1.0001, maximum-scale=1.0001, user-scalable=no"/>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application'%>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

  <%= render :partial => 'shared/navbar' %>
  <div id="wrapper">
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div>
                  <div class="col-sm-1">
                  </div>
                  <div class="col-sm-8">

                     <%= yield %>
                      <div id="user_nav">
                      <% if user_signed_in? %>
                      Signed in as <%= current_user.email %>. Not you?
                      <%= link_to "Sign out", destroy_user_session_path %>
                      <% else %>
                      <%= link_to "Sign up", new_user_registration_path %> or
                      <%= link_to "Sign in", new_user_session_path %>
                      <% end %>
                      </div>
                  </div>
                </div>
            </div>
        </div>
    <div id="myUserForm" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>
  </div>  
  
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
	 <div class="container-fluid">
	 	  <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <a class="navbar-brand" href="#">Midwest Sign Co</a>
		   </div>
		   <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		       <ul class="nav navbar-nav">
		       			<li>
							<%= link_to 'Contacts', contacts_path %>
						</li>
						<li>
							<%= link_to 'TimeTracker', timerecords_path(:selecteduser => current_user.id, :weekstart => $beginning_of_this_week , :weekend => $end_of_this_week) %>
						</li>
						<li>
						<%= link_to 'Employees', users_path if current_user.admin? %>
						</li>
				</ul>
				
		    </div>
	</div>
</nav>

app/views/shared/_sidebar.html.erb
<div id="sidebar-wrapper">
    <ul class="sidebar-nav">
        
    </ul>
</div>