config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users
  root 'contacts#index'

  resources :timerecords
  
  get 'timerecords/timeout/:id' => 'timerecords#timeout'

  
  resources :contacts do
  	resources :locations
    resources :people
  end

  resources :locations do
    resources :signs
  end

  resources :signs do
    resources :sign_details
    resources :jobnumbers
    resources :attributes
  	resources :records
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

  self.abstract_class = true
  $contacts = Contact.all
  d=Date.today
  $beginning_of_this_week = d.at_beginning_of_week-1.day
  $end_of_this_week = d.at_beginning_of_week+6.day

end

app/models/contact.rb
class Contact < ApplicationRecord
	has_many :locations
	has_many :people
	has_many :signs
	has_many :jobnumbers
	has_many :timerecords, through: :jobnumbers
		
  default_scope {order('CompanyName ASC')}
  
		

end

app/models/jobnumber.rb
class Jobnumber < ApplicationRecord
	belongs_to :contact
	belongs_to :sign
	has_many :timerecords
end

app/models/jobnumbers.rb
class Jobnumbers < ActiveRecord::Base
	belongs_to :contact
	belongs_to :sign
	has_many :timerecords
	end

app/models/location.rb
class Location < ApplicationRecord
	belongs_to :contact
	has_many :signs

	scope :matchesContact, ->(id){ where(contact_id: id)}
	

end

app/models/person.rb
class Person < ApplicationRecord
	belongs_to :contact
	
	scope :matchesContact, ->(id){ where(contact_id: id)}
	
end

app/models/record.rb
class Record < ApplicationRecord
	belongs_to :sign
end

app/models/sign.rb
class Sign < ApplicationRecord
	belongs_to :contact
	belongs_to :location, optional: true
	has_many :jobnumbers
	has_many :sign_details
	scope :matchesContactandLocation, ->(id){ where(contact_id: id)}
end

app/models/sign_detail.rb
class SignDetail < ApplicationRecord
	belongs_to :sign
end

app/models/task.rb
class Task < ActiveRecord::Base
	has_many :timerecords
	has_many :users, through: :timerecords
end

app/models/timerecord.rb
class Timerecord < ActiveRecord::Base

	include Filterable

	belongs_to :user
	belongs_to :task

	default_scope {order('timein ASC')}
		
	scope :notimeout, -> {where('timeout IS ?', nil)} 
	scope :timethisweek, -> {where('timein > ?', d).all} 
	scope :weekstart, -> (weekstart){where('timein >= ?', weekstart).all} 
	scope :dateis, -> (date){where('timein = ?', date).all} 
	scope :weekend, -> (weekend){where('timein <= ?', weekend).all} 
	scope :currentuser, ->(user) {where('user_id = ?', user )}
	scope :selecteduser, ->(user) {where('user_id = ?', user )} 
	scope :thisjob, ->(number) {where('jobnumber = ?', number )} 
	scope :tasks_all, ->(taskid){where('task_id = ?', taskid)}
	
	def timeTotal
		if timeout?
			@timeout = timeout
		else
			@timeout = Time.zone.now
		end
		((Time.diff(timein, @timeout, '%m'))[:diff].to_f / 60).round(2)
	end
	
	def day
  		self.timein.strftime('%D')
	end

	d=Time.zone.today
	$timenow = Time.zone.now 
  	$beginning_of_this_week = d.at_beginning_of_week-1.day
  	$end_of_this_week = d.at_beginning_of_week+5.day
  	$beginning_of_last_week = d.at_beginning_of_week-8.day
  	$end_of_last_week = d.at_beginning_of_week-2.day

		
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :timerecords
  has_many :tasks, through: :timerecords

	def fullName
		fullName = "#{firstname} #{lastname}"
	end

end

app/controllers/signs_controller.rb
class SignsController < ApplicationController

    layout 'contact'
	def index
		@contact = Contact.find(params[:id])

		if params[:loc]== "main"
		else
		@location = Location.find(params[:loc])
		end
	end
	def show
		
		@sign= Sign.find(params[:id])

	end

	def new
        @sign = Sign.new
    end
    def create
    	 
    	 @sign = Sign.new(sign_params)
    	 @contact = @sign.contact_id
         if @sign.save
      		redirect_to contact_path(:id => @sign.contact_id), status: 303, format: 'js'
       
     	 end
	end
end
private
    def sign_params
      params.require(:sign).permit(:signDesc, :signLoc, :active, :builtBy, :installDate, :contact_id, :location_id)
    end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :verify_is_admin
  
  layout 'user'

  def index
  	@users=User.all
  	if params[:id]
      @user = User.find(params[:id]).decorate
          respond_to do |format|
            format.html { render "show" }
            format.js { render "show" }
          end
      else
      end
  end

  def show
  	@user = User.find(params[:id])
    respond_to do |format|
      format.html { render "show" }
      format.js { render "show" }
    end
  end

	
	def edit
		@user = User.find(params[:id])
	end

	
	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
		respond_to do |format|
		format.js { render "show" }
		end

		else 

		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy

		redirect_to user_path
	end

	private
	def user_params
		params.require(:user).permit(:email, :firstname, :lastname, :admin, :active)
	end
	
	def verify_is_admin
  		(current_user.nil?) ? redirect_to(root_path) : (redirect_to(root_path) unless current_user.admin?)
	end
	end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/jobnumbers_helper.rb
module JobnumbersHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/sign_details_helper.rb
module SignDetailsHelper
end

app/helpers/signs_helper.rb
module SignsHelper
end

app/helpers/timerecord_helper.rb
module TimerecordHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/signs/_form.html.erb
<%= form_for @sign, remote: true do |f| %>
  <div class="modal-dialog" role="form">
    <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button><h4 class="modal-title" id="myModalLabel"><%= :title%></h4>
    </div>
      <div class="modal-body">

<% if @sign.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@sign.errors.count, "error") %> prohibited
        this sign from being saved:
      </h2>
      <ul>
        <% @sign.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <div class="modalLeft">
      <p>
      <%= f.label :signDesc %><br>
      <%= f.text_field :signDesc %>
       <p>
        <%= f.label :signLoc %><br>
        <%= f.text_field :signLoc %>
      </p>
      <p>
        <%= f.label :active %><br>
        <%= f.check_box :active  %>
      </p>
      <p>
        <%= f.label :builtBy %><br>
        <%= f.text_field :builtBy  %>
      </p>      
      <p>
        <%= f.label :installDate %><br>
        <%= f.date_field :installDate  %>
      </p>
    </div>
    <div class="modalRight">

    </div>
  </div>
  <%=f.hidden_field :contact_id, value: params[:id]%>
  <%=f.hidden_field :location_id, value: params[:loc]%>


<div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit ({ :class => 'btn btn-primary'})%>
        
</div>
</div>
</div>
<% end %>

app/views/signs/_show.html.erb
  <div class="modal-dialog">
    <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button><h4 class="modal-title" id="myModalLabel"><%= @sign.signDesc%> </h4>
    </div>
      <div class="modal-body">


    <div class="modalLeft">
     Location: <%= @sign.signLoc%> 
     <%= render @sign.sign_details%>
    </div>
    <div class="modalRight">
    <%= render @sign.jobnumbers%>
    </div>
  </div>
  


<div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
       
        
</div>
</div>
</div>

app/views/signs/_sign.html.erb
  <div>
  <%= link_to sign.signDesc, sign_path(:id => sign.id) %>
  </div>

app/views/signs/edit.js.erb
$("#myContactForm").html('<%= j render('edit') %>');

app/views/signs/index.html.erb
super dooper

app/views/signs/new.js.erb
$("#myContactForm").html('<%= j render('new') %>');

app/views/signs/show.js.erb
$("#myContactForm").html('<%= j render('show') %>');

app/views/users/_edit.html.erb
<%= render 'form' %>

app/views/users/_form.html.erb
<%= form_for @user, remote: true do |f| %>
  <div class="modal-dialog" role="form">
    <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button><h4 class="modal-title" id="myModalLabel"><%= :title%></h4>
    </div>
      <div class="modal-body">

<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="modalLeft">
    <p>
      <%= f.label :firstname %><br>
      <%= f.text_field :firstname %>
    </p>    
    <p>
      <%= f.label :lastname %><br>
      <%= f.text_field :lastname %>
    </p>    
    <p>
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label :admin %><br>
      <%= f.check_box :admin %>
    </p>
    <p>
      <%= f.label :active %><br>
      <%= f.check_box :active %>
    </p>
  </div>
    <div class="modalRight">
    
    
  </div>
  </div>


<div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit ({ :class => 'btn btn-primary'})%>
        
</div>
</div>
</div>
<% end %>

app/views/users/_new.html.erb
<%= render 'form' %>

app/views/users/_show.html.erb
<div id='user'>
	
  <h2><%= @user.firstname%> <%= @user.lastname %>

 <small>  
 <%= link_to edit_user_path(@user),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#myUserForm'} do  %>
  <span class="glyphicon glyphicon-pencil"></span>
  <%end%>
	<%= link_to user_path(@user),
              method: :delete,
              data: { confirm: 'Are you sure?' } do%>
  <span class="glyphicon glyphicon-remove"></span>
  <%end%>
  </small>
  </h2>

  <div>  
    <div>
      <span><strong>Email: </strong></span>
      <span><%=mail_to @user.email%></span>
      <span><strong>Admin: </strong></span>
      <span><%= check_box_tag 'admin', '1', ('checked' if @user.admin == 1) , :disabled => true %></span>
      <span><strong>Active: </strong></span>
      <span><%= check_box_tag 'active', '1', ('checked' if @user.active == 1) , :disabled => true %></span>
    </div>
  </div>
<%= link_to 'timerecords', timerecords_path(:selecteduser => @user, :weekstart => $beginning_of_this_week, :weekend => $end_of_this_week)%>

app/views/users/edit.html.erb
<%= render 'edit' %>

app/views/users/edit.js.erb
$("#myUserForm").html('<%= j render('edit') %>');

app/views/users/index.html.erb
<div class="search">
	<%= form_tag(users_path, :method => "get", id: "search-form", remote: true) do %>
		<div class="form-group searchText">
			<%= select_tag "id", options_from_collection_for_select(@users,"id", :fullName, params[:search]), id: "search", include_blank: true, :onchange => "$(this.form).submit();", style: "width: 75%" %>
		</div>
	<% end %>
</div>
<div id="user"></div>

app/views/users/new.js.erb
$("#myUserForm").html('<%= j render('new') %>');

app/views/users/show.html.erb
<%= render 'show' %>

app/views/users/show.js.erb
$('#myUserForm').modal('hide');
$('.modal-backdrop').remove();
$("body").removeClass("modal-open");
$('#user').replaceWith('<%= j render('show') %>');