config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users
  root 'contacts#index'

  resources :timerecords
  
  get 'timerecords/timeout/:id' => 'timerecords#timeout'

  
  resources :contacts do
  	resources :locations
    resources :people
  end

  resources :locations do
    resources :signs
  end

  resources :signs do
    resources :sign_details
    resources :jobnumbers
    resources :attributes
  	resources :records
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

  self.abstract_class = true
  $contacts = Contact.all
  d=Date.today
  $beginning_of_this_week = d.at_beginning_of_week-1.day
  $end_of_this_week = d.at_beginning_of_week+6.day

end

app/models/contact.rb
class Contact < ApplicationRecord
	has_many :locations
	has_many :people
	has_many :signs
	has_many :jobnumbers
	has_many :timerecords, through: :jobnumbers
		
  default_scope {order('CompanyName ASC')}
  
		

end

app/models/jobnumber.rb
class Jobnumber < ApplicationRecord
	belongs_to :contact
	belongs_to :sign
	has_many :timerecords
end

app/models/jobnumbers.rb
class Jobnumbers < ActiveRecord::Base
	belongs_to :contact
	belongs_to :sign
	has_many :timerecords
	end

app/models/location.rb
class Location < ApplicationRecord
	belongs_to :contact
	has_many :signs

	scope :matchesContact, ->(id){ where(contact_id: id)}
	

end

app/models/person.rb
class Person < ApplicationRecord
	belongs_to :contact
	
	scope :matchesContact, ->(id){ where(contact_id: id)}
	
end

app/models/record.rb
class Record < ApplicationRecord
	belongs_to :sign
end

app/models/sign.rb
class Sign < ApplicationRecord
	belongs_to :contact
	belongs_to :location, optional: true
	has_many :jobnumbers
	has_many :sign_details
	scope :matchesContactandLocation, ->(id){ where(contact_id: id)}
end

app/models/sign_detail.rb
class SignDetail < ApplicationRecord
	belongs_to :sign
end

app/models/task.rb
class Task < ActiveRecord::Base
	has_many :timerecords
	has_many :users, through: :timerecords
end

app/models/timerecord.rb
class Timerecord < ActiveRecord::Base

	include Filterable

	belongs_to :user
	belongs_to :task

	default_scope {order('timein ASC')}
		
	scope :notimeout, -> {where('timeout IS ?', nil)} 
	scope :timethisweek, -> {where('timein > ?', d).all} 
	scope :weekstart, -> (weekstart){where('timein >= ?', weekstart).all} 
	scope :dateis, -> (date){where('timein = ?', date).all} 
	scope :weekend, -> (weekend){where('timein <= ?', weekend).all} 
	scope :currentuser, ->(user) {where('user_id = ?', user )}
	scope :selecteduser, ->(user) {where('user_id = ?', user )} 
	scope :thisjob, ->(number) {where('jobnumber = ?', number )} 
	scope :tasks_all, ->(taskid){where('task_id = ?', taskid)}
	
	def timeTotal
		if timeout?
			@timeout = timeout
		else
			@timeout = Time.zone.now
		end
		((Time.diff(timein, @timeout, '%m'))[:diff].to_f / 60).round(2)
	end
	
	def day
  		self.timein.strftime('%D')
	end

	d=Time.zone.today
	$timenow = Time.zone.now 
  	$beginning_of_this_week = d.at_beginning_of_week-1.day
  	$end_of_this_week = d.at_beginning_of_week+5.day
  	$beginning_of_last_week = d.at_beginning_of_week-8.day
  	$end_of_last_week = d.at_beginning_of_week-2.day

		
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :timerecords
  has_many :tasks, through: :timerecords

	def fullName
		fullName = "#{firstname} #{lastname}"
	end

end

app/controllers/contacts_controller.rb
 
class ContactsController < ApplicationController
 
    layout 'contact'
    def new
        @contact = Contact.new
    end
    def edit
        @contact = Contact.find(params[:id])
    end
    
    def index
      @location = Location.new
      @person = Person.new
      @contacts = Contact.all.order('CompanyName asc')
      if params[:id]
      @contact = Contact.find(params[:id])
          respond_to do |format|
            format.html { render "show" }
            format.js { render "show" }
          end
      else
      end
    end

    def show
    @contact = Contact.find(params[:id])
    @location = Location.new
    @person = Person.new
        respond_to do |format|
          format.html { render "show" }
          format.js { render "show" }
        end
    end
        
    def create
        @contact = Contact.new(contact_params)
        if @contact.save
            respond_to do |format|
                format.js { render "show" }
            end
        else
            
        end
    end

    def update
        @contact = Contact.find(params[:id])
        if @contact.update(contact_params)
            respond_to do |format|
                format.js { render "show" }
            end
        
        else 
            
        end
    end

    def destroy
        @contact = Contact.find(params[:id])
        @contact.destroy

        redirect_to contacts_path
    end
    
    private
    def contact_params
        params.require(:contact).permit(:CompanyName, :Address, :Address1, :City, :StateOrProvince, :PostalCode, :WorkPhone, :FaxNumber)
    end
end

app/controllers/signs_controller.rb
class SignsController < ApplicationController

    layout 'contact'
	def index
		@contact = Contact.find(params[:id])

		if params[:loc]== "main"
		else
		@location = Location.find(params[:loc])
		end
	end
	def show
		
		@sign= Sign.find(params[:id])

	end

	def new
        @sign = Sign.new
    end
    def create
    	 
    	 @sign = Sign.new(sign_params)
    	 @contact = @sign.contact_id
         if @sign.save
      		redirect_to contact_path(:id => @sign.contact_id), status: 303, format: 'js'
       
     	 end
	end
end
private
    def sign_params
      params.require(:sign).permit(:signDesc, :signLoc, :active, :builtBy, :installDate, :contact_id, :location_id)
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/jobnumbers_helper.rb
module JobnumbersHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/sign_details_helper.rb
module SignDetailsHelper
end

app/helpers/signs_helper.rb
module SignsHelper
end

app/helpers/timerecord_helper.rb
module TimerecordHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_contact.html.erb
<div class="thumbnail">
<div class="col-sm-8 leftThumbnail">
  <div>
    <span><strong>Name: </strong></span>
    <span class="alignRight"><%= contact.Title %><%= contact.FirstName%> <%= contact.LastName %></span>
  </div>
  <div>
    <span><strong>Cell Phone: </strong></span>
    <span class="alignRight"><%= number_to_phone(contact.MobilePhone, area_code: true)%></span>
  </div>
  <div>
    <span><strong>Email: </strong></span>
    <span class="alignRight"><%=mail_to contact.EmailName%></span>
  </div>
  <div>
      <span><strong><%= link_to "Current Signs", sign_path(:id => @contact.id, :loc => 'main'), {:remote => true, 'data-toggle' => "modal", 'data-target' => '#myContactForm'} %></strong></span>
  </div>
  <div>
      <%= link_to 'Add a sign to this location', new_sign_path(:id => @contact.id, :loc => 'main'), {:remote => true, 'data-toggle' => "modal", 'data-target' => '#myContactForm'} %>
  </div>
</div>
<div class="col-sm-8 rightThumbnail">
  <strong>Address:</strong>
  <p><%= contact.Address%></p>
  <p><%= contact.Address1 %></p>
  <p><%= contact.City%> <%=contact.StateOrProvince %> <%=contact.PostalCode %></p>
  
  <p><%= link_to "Go to map", "https://www.google.com/maps/search/"+ contact.Address+" "+contact.City+" "+contact.StateOrProvince+" "+contact.PostalCode %></p>

  <strong>phone:</strong>
  
  <p><%= number_to_phone(contact.WorkPhone, area_code: true) %></p>
  <strong>fax:</strong>
  <p><%= number_to_phone(contact.FaxNumber, area_code: true) %></p>
</div>
  

</div>

app/views/contacts/_form.html.erb
<%= form_for @contact, remote: true do |f| %>
  <div class="modal-dialog" role="form">
    <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button><h4 class="modal-title" id="myModalLabel"><%= :title%></h4>
    </div>
      <div class="modal-body">

<% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@contact.errors.count, "error") %> prohibited
        this contact from being saved:
      </h2>
      <ul>
        <% @contact.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="modalLeft">
    <p>
    <%= f.label :CompanyName %><br>
    <%= f.text_field :CompanyName %>
     <p>
      <%= f.label :Address %><br>
      <%= f.text_field :Address %><br>
      <%= f.text_field :Address1 %>
    </p>
    <p>
      <%= f.text_field :City ,:size=>20 %>
      <%= f.text_field :StateOrProvince ,:size=>2 %>
      <%= f.text_field :PostalCode ,:size=>5%>
    </p>
    <p>
      <%= f.label :WorkPhone %><br>
      <%= f.telephone_field(:WorkPhone) %>
    </p>
    <p>
      <%= f.label :FaxNumber %><br>
      <%= f.telephone_field(:FaxNumber) %>
    </p>
  </div>
    <div class="modalRight">
    <p>
      <%= f.label :FirstName %><br>
      <%= f.text_field :FirstName %>
    </p>    
    <p>
      <%= f.label :LastName %><br>
      <%= f.text_field :LastName %>
    </p>
    
  </div>
  </div>


<div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit ({ :class => 'btn btn-primary'})%>
        
</div>
</div>
</div>
<% end %>

app/views/contacts/_links.html.erb
<div class="btn-group" role="group" aria-label="...">
<%= link_to 'New Company', new_contact_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#myContactForm', :method => "get", "class" => "btn btn-primary"} %>
<%= link_to 'Add Location', new_contact_location_path(@contact, @location),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#myContactForm', :method => "get", "class" => "btn btn-primary"} %>
<%= link_to 'Add Contact', new_contact_person_path(@contact, @person),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#myContactForm', :method => "get", "class" => "btn btn-primary"} %>
</div>

app/views/contacts/_new.html.erb
<%= render 'form', locals: {title: "Products Page"}  %>

app/views/contacts/_search.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
	 <div class="container-fluid">
	 	  <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <a class="navbar-brand" href="#">Midwest Sign Co</a>
		   </div>
		   <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      	<ul class="nav navbar-nav">
	     		  <li><%= link_to 'New Contact', new_contact_path, remote: true%></li>
				  </ul>
			 <%= form_tag(contacts_path, :method => "get", id: "search-form",  class: "navbar-form navbar-left", remote: true) do %>
       <div class="form-group">

				<%= select_tag "id", options_from_collection_for_select($contacts,"id", "CompanyName", params[:search]), id: "search", include_blank: true, :onchange => "$(this.form).submit();"%>
        </div>
			<% end %>
		    </div>
	</div>
</nav>

app/views/contacts/_show.html.erb
<div id='contact'>
	
  <h2><%=@contact.CompanyName %>

 <small>  
 <%= link_to edit_contact_path(@contact),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#myContactForm'} do  %>
  <span class="glyphicon glyphicon-pencil"></span>
  <%end%>
	<%= link_to contact_path(@contact),
              method: :delete,
              data: { confirm: 'Are you sure?' } do%>
  <span class="glyphicon glyphicon-remove"></span>
  <%end%>
  </small>
  </h2>

  <div>
   
      <%= render @contact%>
      <h3> Additional Contacts </h3>
      <%= render @contact.people%>
      <h3> Additional Locations </h3>
      <%= render @contact.locations%>


 
  </div>
</div>   

app/views/contacts/edit.html.erb
<h1> Edit Contact </h1>
<%= render 'form' %>
 <%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<div class="search">
	<%= form_tag(contacts_path, :method => "get", id: "search-form", remote: true) do %>
		<div class="form-group searchText">
			<%= select_tag "id", options_from_collection_for_select($contacts,"id", "CompanyName", params[:search]), id: "search", include_blank: true, :onchange => "$(this.form).submit();"%>
		</div>
	<% end %>
</div>
<div class="company">
	<span>
		<%= button_to 'New Company', new_contact_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#myContactForm', :method => "get", "class" => "btn btn-primary"} %>
	</span>
</div>	
	     		  	
<div id="contact"></div>

app/views/contacts/show.js.erb
$('.company').html(" ");
$('#myContactForm').modal('hide');
$('.modal-backdrop').remove();
$("body").removeClass("modal-open");
$('#contact').replaceWith('<%= j render('show') %>');
$('.company').append('<%= j render('links') %>');