config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users
  root 'contacts#index'

  resources :timerecords
  
  get 'timerecords/timeout/:id' => 'timerecords#timeout'

  
  resources :contacts do
  	resources :locations
    resources :people
  end

  resources :locations do
    resources :signs
  end

  resources :signs do
    resources :sign_details
    resources :jobnumbers
    resources :attributes
  	resources :records
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

  self.abstract_class = true
  $contacts = Contact.all
  d=Date.today
  $beginning_of_this_week = d.at_beginning_of_week-1.day
  $end_of_this_week = d.at_beginning_of_week+6.day

end

app/models/contact.rb
class Contact < ApplicationRecord
	has_many :locations
	has_many :people
	has_many :signs
	has_many :jobnumbers
	has_many :timerecords, through: :jobnumbers
		
  default_scope {order('CompanyName ASC')}
  
		

end

app/models/jobnumber.rb
class Jobnumber < ApplicationRecord
	belongs_to :contact
	belongs_to :sign
	has_many :timerecords
end

app/models/jobnumbers.rb
class Jobnumbers < ActiveRecord::Base
	belongs_to :contact
	belongs_to :sign
	has_many :timerecords
	end

app/models/location.rb
class Location < ApplicationRecord
	belongs_to :contact
	has_many :signs

	scope :matchesContact, ->(id){ where(contact_id: id)}
	

end

app/models/person.rb
class Person < ApplicationRecord
	belongs_to :contact
	
	scope :matchesContact, ->(id){ where(contact_id: id)}
	
end

app/models/record.rb
class Record < ApplicationRecord
	belongs_to :sign
end

app/models/sign.rb
class Sign < ApplicationRecord
	belongs_to :contact
	belongs_to :location, optional: true
	has_many :jobnumbers
	has_many :sign_details
	scope :matchesContactandLocation, ->(id){ where(contact_id: id)}
end

app/models/sign_detail.rb
class SignDetail < ApplicationRecord
	belongs_to :sign
end

app/models/task.rb
class Task < ActiveRecord::Base
	has_many :timerecords
	has_many :users, through: :timerecords
end

app/models/timerecord.rb
class Timerecord < ActiveRecord::Base

	include Filterable

	belongs_to :user
	belongs_to :task

	default_scope {order('timein ASC')}
		
	scope :notimeout, -> {where('timeout IS ?', nil)} 
	scope :timethisweek, -> {where('timein > ?', d).all} 
	scope :weekstart, -> (weekstart){where('timein >= ?', weekstart).all} 
	scope :dateis, -> (date){where('timein = ?', date).all} 
	scope :weekend, -> (weekend){where('timein <= ?', weekend).all} 
	scope :currentuser, ->(user) {where('user_id = ?', user )}
	scope :selecteduser, ->(user) {where('user_id = ?', user )} 
	scope :thisjob, ->(number) {where('jobnumber = ?', number )} 
	scope :tasks_all, ->(taskid){where('task_id = ?', taskid)}
	
	def timeTotal
		if timeout?
			@timeout = timeout
		else
			@timeout = Time.zone.now
		end
		((Time.diff(timein, @timeout, '%m'))[:diff].to_f / 60).round(2)
	end
	
	def day
  		self.timein.strftime('%D')
	end

	d=Time.zone.today
	$timenow = Time.zone.now 
  	$beginning_of_this_week = d.at_beginning_of_week-1.day
  	$end_of_this_week = d.at_beginning_of_week+5.day
  	$beginning_of_last_week = d.at_beginning_of_week-8.day
  	$end_of_last_week = d.at_beginning_of_week-2.day

		
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :timerecords
  has_many :tasks, through: :timerecords

	def fullName
		fullName = "#{firstname} #{lastname}"
	end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  layout 'loggedin'
  def index
    
    if params[:id]
      @contact = Contact.find(params[:id])
      @locations = Location.matchesContact(params[:id])
      @location = Location.new
        respond_to do |format|
          format.html { render "show" }
          format.js { render "show" }
        end
     
    else
    end
  end
  def show
    
    @locations = Location.find(params[:id])
    @contact = Contact.find(params[:contact_id])
    
    @location = Location.new
      respond_to do |format|
        format.html { render "show" }
        format.js { render "show" }
      end
  end
  def new
    @location = Location.new
    @contact = Contact.find(params[:contact_id])
  end
  def edit
    @location = Location.find(params[:id])
    @contact = Contact.find(params[:contact_id])
  end	

  def update
    @location = Location.find(params[:id])
    if @location.update(location_params)
      redirect_to contact_path(params[:contact_id]), format: 'js'
      
    else 

    end
  end

  def create
    @contact = Contact.find(params[:contact_id])
    @location = @contact.locations.create(location_params)
    flash[:notice] = "Location was successfully created." 
     if @location.save
      redirect_to contact_path(params[:contact_id]), status: 303, format: 'js'
       
     end
	end
  def destroy
    @contact = Contact.find(params[:contact_id])
    @location = @contact.locations.find(params[:id])
    @location.destroy
      redirect_to contact_path(params[:contact_id]), status: 303, format: 'js'
       
  end
end
 
  private
    def location_params
      params.require(:location).permit(:locationName, :onsiteContactName, :Address, :Address1, :City, :StateOrProvince, :PostalCode, :WorkPhone, :FaxNumber, :notes)
    end

app/controllers/signs_controller.rb
class SignsController < ApplicationController

    layout 'contact'
	def index
		@contact = Contact.find(params[:id])

		if params[:loc]== "main"
		else
		@location = Location.find(params[:loc])
		end
	end
	def show
		
		@sign= Sign.find(params[:id])

	end

	def new
        @sign = Sign.new
    end
    def create
    	 
    	 @sign = Sign.new(sign_params)
    	 @contact = @sign.contact_id
         if @sign.save
      		redirect_to contact_path(:id => @sign.contact_id), status: 303, format: 'js'
       
     	 end
	end
end
private
    def sign_params
      params.require(:sign).permit(:signDesc, :signLoc, :active, :builtBy, :installDate, :contact_id, :location_id)
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/jobnumbers_helper.rb
module JobnumbersHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/sign_details_helper.rb
module SignDetailsHelper
end

app/helpers/signs_helper.rb
module SignsHelper
end

app/helpers/timerecord_helper.rb
module TimerecordHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/locations/_form.html.erb
<!-- Modal -->
<%= form_for [@contact, @location], remote: true do |f| %>
  <div class="modal-dialog" role="form">
    <div class="modal-content">
      <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button><h4 class="modal-title" id="myModalLabel">New Location</h4>
      </div>
      <div class="modal-body">
         <div class="modalLeft">
        <p>
          <%= f.label :locationName %><br>
          <p><%= f.text_field :locationName %></p>
        </p>  
        <p>
          <%= f.label :onsiteContactName %><br>
          <p><%= f.text_field :onsiteContactName %></p>
        </p>
        <p>
          <%= f.label :Address %><br>
          <p><%= f.text_field :Address %></p>
          <p><%= f.text_field :Address1 %></p>
        </p>
        <p>
        	<%= f.text_field :City ,:size=>20 %>
        	<%= f.text_field :StateOrProvince ,:size=>2 %>
        	<%= f.text_field :PostalCode ,:size=>5%>
        </p>
        <p>
          <%= f.label :WorkPhone %><br>
          <%= f.telephone_field(:WorkPhone) %>
        </p>
        <p>
          <%= f.label :FaxNumber %><br>
          <%= f.telephone_field(:FaxNumber) %>
        </p>
        <p>
          <%= f.label :notes %><br>
          <%= f.text_area(:notes) %>
        </p>
           </div> 
          
           </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit ({ :class => 'btn btn-primary' })%>
          </div>

      </div>
    </div>
  </div>
<% end %>

app/views/locations/_location.html.erb
  <div>
  <%= link_to location.locationName,  contact_location_path(:id => location.id, :contact_id => @contact.id), {:remote => true} %>
  </div>

app/views/locations/_show.html.erb
<div id='contact'>
  
  <h3><%=@contact.CompanyName %>

 <small>  
 <%= link_to edit_contact_path(@contact),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#myContactForm'} do  %>
  <span class="glyphicon glyphicon-pencil"></span>
  <%end%>
  <%= link_to contact_path(@contact),
              method: :delete,
              data: { confirm: 'Are you sure?' } do%>
  <span class="glyphicon glyphicon-remove"></span>
  <%end%>
  <%= link_to "Back to Main Contact", contact_path(@contact), {:remote => true} %>
  </small>
  </h3>
 <h2><%=@locations.locationName%>
      <small>
      
        <%= link_to edit_contact_location_path(@contact, @locations.id), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#myContactForm'} do  %>
          <span class="glyphicon glyphicon-pencil"></span>
        <%end%>
        <%= link_to [@locations.contact, @locations],
            method: :delete,
            data: { confirm: 'Are you sure?' },
            remote: true do%>
          <span class="glyphicon glyphicon-remove"></span>
        <%end%>

      </small>
    </h2>
  
  <div>
   
      <div class="thumbnail">
  <div class="col-sm-8">
    
    <div> <strong>Contact:</strong><%=@locations.onsiteContactName%> </div>
    
    <div>
      <span><strong>Current Signs</strong></span>
      <%= render @locations.signs%>
    </div>
    <div>
      <%= link_to 'Add a sign to this location', new_sign_path(:id => @contact.id, :loc => @locations.id), {:remote => true, 'data-toggle' => "modal", 'data-target' => '#myContactForm'} %>
    </div>
  </div>
  <div class="col-sm-8 rightThumbnail">
    <strong>Address:</strong>
    <p><%= @locations.Address%></p>
    <p><%= @locations.Address1 %></p>
    <p><%= @locations.City%> <%=@locations.StateOrProvince %><%=@locations.PostalCode %></p>
    <p><%= link_to "Go to map", "https://www.google.com/maps/search/"+@locations.Address+@locations.City+@locations.StateOrProvince+@locations.PostalCode%></p>
    <strong>phone:</strong>
    <p><%=number_to_phone(@locations.WorkPhone, area_code: true)%></p>
    <strong>fax:</strong>
    <p><%=number_to_phone(@locations.FaxNumber, area_code: true)%></p>
    <strong>Notes:</strong>
    <p> <%=@locations.notes%> </p>
  </div>
</div>
       
  </div>
</div> 

app/views/locations/show.html.erb
<%= render 'show' %>

app/views/locations/show.js.erb
$('#contact').replaceWith('<%= j render('show') %>');